### ISSUE TITLE
hasql 2.0?

### ISSUE THREAD

**Issue by steshaw** [nikita-volkov/hasql#114]
Hi, I was looking for hasql 2.0 from [this talk](https://www.youtube.com/watch?v=L8-iC4_E5n4). Where could I find it?

**Comment by nikita-volkov** [comment]
It still resides in the beta. The developments are released under the 0.20.* version, but its not production-ready yet unfortunately.

**Comment by steshaw** [comment]
No worries! I see it, it's the ~dev~ branch here. It's not been updated for a couple of years.

I was really excited by the talk. Were there any particular issues that keep it in beta?

**Comment by nikita-volkov** [comment]
> It's not been updated for a couple of years.

True. I just don't get much time lately. I still do plan to finish this thing.

> Were there any particular issues that keep it in beta?

Yes. GC. I've had several goes at the implementation and profiling and whatever I've tried didn't give me satisfactory results in terms of performance.

**Comment by steshaw** [comment]
No worries, thanks for the info. It's a noble pursuit and I wish you the best. Perhaps I can help in some way? I'm not experienced with Haskell profiling but one learns by doing. Maybe some data structures could be moved off-heap?

**Comment by nikita-volkov** [comment]
Sure. You're welcome to analyse and experiment with the dev branch and ask me detailed questions.

**Comment by avanov** [comment]
Hi! I've been wondering about this dev branch lately, particularly in relation to `postgresql-typed`: https://github.com/dylex/postgresql-typed/issues/26

What is your long-term plan regarding the 0.20.* branch? Is it likely to be deprecated due to the mentioned GC limitations or to be officially released as 2.x at some point in future?

I also wonder if/how `postgresql-typed` managed to avoid these GC issues in their implementation.

**Comment by nikita-volkov** [comment]
Hey! The issues have been resolved and the performance results are great :) The new developments will be released in the coming months as a new project. See https://twitter.com/NikitaYVolkov/status/1452985041366175750

**Comment by avanov** [comment]
very nice, thank you!
