### ISSUE TITLE
Add dist-newstyle to .gitignore

### ISSUE THREAD

**Issue by jfischoff** [nikita-volkov/hasql#124]

**Comment by nikita-volkov** [comment]
I'm one of the proponents of not distributing `.gitignore` with the source code. This allows everyone to have their own version of it, which is specific to their development environment, it removes that from concerns of the repository instead of everyone PR-ing with their tweaks to it, and it still allows everyone to have `.gitignore` without problem by just listing `.gitignore` in itself.

**Comment by jfischoff** [comment]
Sounds good. Closing
