### ISSUE TITLE
Add instructive README

### ISSUE THREAD

**Issue by Jonplussed** [nikita-volkov/hasql#13]
Hasql is awesome, but different enough from existing Haskell database libraries that using it can be initially puzzling to use. I think an instructive README in the repo (and linked from Hackage) could go a long way towards helping users get situated with Hasql.

If you're cool with adding a README to the project, I'm happy to write up a draft, which you'd of course be free to splice as suits you.

**Comment by wiz** [comment]
Please keep a changelog[1] too. A kitten cries each time someone's seeing "Change log: not available" on hackage.

[1]: http://keepachangelog.com/

**Comment by nikita-volkov** [comment]
@wiz I understand your concern. However it's really tough to maintain such things. Very often things get left out of the changelogs simply because the maintainers forget to include them. I hardly manage to keep up with my existing responsibilities and adding yet another one doesn't sound very fun to me.
