### ISSUE TITLE
Performance of hasql with Odyssey

### ISSUE THREAD

**Issue by viviag** [nikita-volkov/hasql#148]
We have a bunch of hasql-based applications connecting the same cloud database through Odyssey. We observed for a long time that if we perform load test of app `A`, we get alerts on slow responses on app `B`. In all observed cases no system limit on both database cluster and worker was hit.
This situation is not observed when we generate load with `pgbench`.

To reproduce the situation we (with @aeifn) have conducted [research](https://github.com/pandora-mccme/hasql-loadtest#readme). Please take a look.

**Comment by nikita-volkov** [comment]
Unless you're able to pinpoint a specific issue in Hasql I'm afraid I won't be able to help. For now the issue seems too vague and the reproduction is complicated enough for the actual cause to be hiding in your setup. As I hope you understand I cannot invest time in such situations.

Regarding

> hypothesis that hasql holds connections longer than necessary or something like that

You have full control over how long Hasql holds the connections via the `acquire` and `release` functions. So I recommend investigating whether you're using it right.
