### ISSUE TITLE
Encoding Text to enum types?

### ISSUE THREAD

**Issue by 0x777** [nikita-volkov/hasql#16]
Inserting a value into a postgres enum type through hasql gives an error. How can I insert a value into a column with enum type defined in postgres as `CREATE TYPE mood AS ENUM ('sad', 'ok', 'happy')`?

**Comment by arkhamist** [comment]
I don't see how it is a hack. Postgres has an `enum` type and I feel that it makes sense to have a corresponding Haskell type. Unfortunately, postgres's binary protocol doesn't seem to support an array of `enum`s. As I understand, it means that `PGEnum` can't be an instance of `ArrayMapping`. And if anyone tries to use an array of `enum` type, they would simply see the same (at compile time). Why? because postgres's binary protocol does not support it. 

The `Unknown` type seems to do the trick. However, it feels more like a hack since I already know the type of the value I'm trying to encode. And more importantly, I could write potentially dangerous code because of the broad range of implicit coercions of unknown type.

**Comment by nikita-volkov** [comment]
> Postgres has an enum type and I feel that it makes sense to have a corresponding Haskell type.

Neither Postgres, nor Haskell has an "enum" type. Both have ways to construct a specific "enum" type, but that's a different thing. The problem is that there can be no predefined Postgres type to map to from the Haskell side, it's always application-specific.

The reason I didn't merge this pull request as it was was that it was essentially implemented the same way as `Unknown` (please, pardon the triple "was", but then it's just the 2nd of January here).  And neither could it serve as a well-defined solution to the "enum" problem (e.g., on top of the "arrays" problem, there was a "unicode" problem at least) nor did it seem to provide anything on top of the more general "Unknown" wrapper.

> I could write potentially dangerous code because of the broad range of implicit coercions of unknown type.

I hate to break it to you, but you always can write a potentially dangerous code. The fact is that it's not the job of a database connection layer to think this thru for you. In case of Hasql the mission is quite simple in this regard: present a communication with a DB using Haskell types. Since, as previously mentioned, "enum" is not exactly a type, here we are.

**Comment by reygoch** [comment]
@nikita-volkov so how is this solved today? I've used the `enum` functions from `Encoders` and `Decoders` modules, but when I run my tests they fail. With the following message:

```
predicate failed on:
SessionError (
	QueryError "
		insert into "Ingredient"
				( name, image, description, unit, price )
		values
				( $1, $2, $3, $4, $5 )
		returning
				id, name, image, description, unit, price;
		"
	["Ing05",null,null,"Kg",34.1]

	( ResultError
		( ServerError "42804"
			"column "unit" is of type unit but expression is of type text"
			Nothing
			( Just "You will need to rewrite or cast the expression." )
		)
	)
)
```

Is the only solution to convert my schema to use `text` instead of my custom `unit` enum type?

**Comment by nikita-volkov** [comment]
@reygoch Have you tried explicit casting? E.g., `values ( $1, $2, $3, $4 :: unit, $5 )`?

**Comment by reygoch** [comment]
@nikita-volkov oh wow, I'm dumb. Totally forgot that this is an option since I'm the one writing the query :D

Thanks!

**Comment by nikita-volkov** [comment]
👍 :)
