### ISSUE TITLE
Building SQL from subexpressions

### ISSUE THREAD

**Issue by sdiehl** [nikita-volkov/hasql#30]
By usual SQL workflow usually involves building up a large SQL statement from several subexpressions, which is currently a bit convoluted to do with the current quasiquoter since there is currently no ``CxValue`` instance for the ``Stmt`` themselves. Ideally something like the following, I'm curious if this  possible in the implementation?

```haskell
predicate :: H.Stmt HP.Postgres
predicate = [H.stmt|LIMIT 3|]

select :: H.Stmt HP.Postgres
select = [H.stmt|SELECT * FROM table ?|] predicate
```

My current workaround involves basically just dropping down to the underlying string type and using the following types to manipulate the underlying string.

```haskell
instance IsString (HB.Stmt a) where
  fromString text = (HB.Stmt (T.pack text) mempty True)

toStmt :: Text -> HB.Stmt c
toStmt x = fromString (T.unpack x)

toText :: HB.Stmt c -> Text
toText (HB.Stmt a _ _) = a
```

**Comment by nikita-volkov** [comment]
`CxValue` is meant solely for mapping of Haskell types to their SQL representations. Since there is no SQL type for statements themselves, such an instance simply doesn't make sense.

SQL is a human-readable language, intended for clear definition of data access. Using another language to glue SQL snippets together in an attempt to elude typing a few extra characters comes at a cost of obfuscating your intent the same way as macro programming does. Hasql's API follows this philosophy and aims to be simply a bridge between Haskell and SQL. That is why Hasql expects you to always write complete statements and to utilise the features of the database for code reuse and composition (e.g., stored procedures, functions, statement references).

**Comment by sdiehl** [comment]
Ok, just curious if it was possible. The example I gave was kind of contrived just to illustrate the concept, but my actual statements are large queries dynamically generated at runtime to do some complex analysis based on some user input and the restriction of having to describe the entire structure of the query at compile-time is too limiting.

Though, I can hack at the internal data structures to get at the Text and workaround the quasiquoter restriction so it's not too big of a deal.

**Comment by nikita-volkov** [comment]
In case your sole requirement is for dynamic statements, the points I made in [this discussion](https://github.com/nikita-volkov/hasql/issues/2) may be of interest to you. In short, the abstraction level provided by the "hasql" API targets the end-users. If what you're working on is some library providing abstractions over SQL, you need to work with "hasql-backend" directly.
