### ISSUE TITLE
Decodable and Encodable classes

### ISSUE THREAD

**Issue by jkarni** [nikita-volkov/hasql#52]
Would a PR adding the classes:

```
class Encodable a where
  encode :: Params a

class Decodable a where
  decode :: Row a
```

With generic instances for them be welcome? I found myself wanting this and wrote it as a separate [package](https://github.com/turingjmp/hasql-class). 

One downside is that the desired behavior for sum types is not obvious, but we could rule out classes with sum types.

**Comment by nikita-volkov** [comment]
This is already achieved with the `Default` instances. You can simply use `def` instead of `encode` or `decode` of your classes.

**Comment by jkarni** [comment]
How do you use generics for default instances in that case?

**Comment by nikita-volkov** [comment]
Oh I see. Well, I haven't studied that, but for a reason. You see, the instances for composite types  in the spirit of the "*-simple" family are a mistake, because they create a leaky abstraction. I.e., while you're seemingly abstracted from the mapping of the contents of the composite value, you need to be aware of how the mapping goes in it to correctly match the placeholders in SQL.

Hence the explicit codec specification is not boilerplate, but specification. I.e., how a certain value gets (de)composed is determined by the SQL statement, not the Haskell type. Which is why it should be explicitly specified with the statement, and that is what the current API encourages.

So I am highly skeptical of implicit definitions here and actually am considering moving the `Default` instances to a separate package. BTW, I've only defined those instances in hope that people won't suggest to recreate the `FromRow`, `ToRow` stuff :)

**Comment by jkarni** [comment]
That's a fair point; I had added a note about precisely this in the `hasql-class` haddocks, and it does feel wrong. There may be syntactic sugar for queries that could make the abstraction not leaky again - roughly, substituting each placeholder by the number of placeholders insider the corresponding type - but this feels like it needs to be thought out more (since for example, having multiple substitutions via a tuple then seems wrong since arguably a tuple shouldn't behave differently than other product types), and probably wouldn't belong in the core package anyhow.

I'm happy closing this; if I feel like I have a more complete solution, I'll open another issue or re-open this.

**Comment by nikita-volkov** [comment]
Good. Thanks for your input.

> having multiple substitutions via a tuple then seems wrong since arguably a tuple shouldn't behave differently than other product types

While, as I've said, I am not a fan of the implicit stuff, I disagree here a little. Tuples at least convey more useful information in that regard: the amount of elements, from which we can derive the amount of placeholders; the specific types that they are composed from, which let us derive their codecs; the stable rules, according to which their decomposition goes.

**Comment by wedens** [comment]
@jkarni  IMHO depending on column names is more reliable than depending on position in result

**Comment by jkarni** [comment]
Cool, I'll play around with ideas in the other repo when I have some time and report back if I do anything interesting.

**Comment by saurabhnanda** [comment]
Is there a way to write a generic row-decoder in HASQL, which depends on column names, on the lines of https://github.com/cocreature/postgresql-named ?

**Comment by nikita-volkov** [comment]
@saurabhnanda Nope

**Comment by saurabhnanda** [comment]
@nikita-volkov is it because of an overarching design decision, or because no one has spent the time in evolving the decoding infra to also provide column names?

**Comment by nikita-volkov** [comment]
@saurabhnanda It is because the results are decoded by their positions, not column names.
