### ISSUE TITLE
Question: Why use MVar? (Streaming support)

### ISSUE THREAD

**Issue by dogirardo** [nikita-volkov/hasql#54]
I'm trying to implement streaming support (foldrRows doesn't seem to cut it, since it builds the whole stream in the IORef first). The translation is straightforward except in `statement` where the interaction with the MVar is difficult to handle in a stream. Rather than reimplementing and running into a wall, I'm hoping you could give some insight on the design choice for using the MVar/IORef throughout.

**Comment by nikita-volkov** [comment]
You don't need to deal with the internals of Hasql at all to be able to implement streaming. I've long been planning to release "hasql-stream" as an extension library myself. I suggest you take the same route.

As for MVar see https://github.com/nikita-volkov/hasql/pull/42.

**Comment by dogirardo** [comment]
Thanks,
Is there skeleton code for your approach to streaming implementation? My tests show fold/foldr Rows build up the whole steam in memory first

**Comment by nikita-volkov** [comment]
See https://github.com/nikita-volkov/hasql-streaming. The codebase there is a bit outdated and will not compile, since it refers to some of my unpublished libraries. However it should give you some ideas.

> My tests show fold/foldr Rows build up the whole steam in memory first

True. But it's a limitation of the lower-level "libpq" library, which Hasql is built around. Unfortunately it's impossible to work around that.

Streaming can only be implemented around Postgres' Cursor feature, using which you split the result of a query into batches.

**Comment by nikita-volkov** [comment]
Actually I've just went on and finished the implementation of the thing, while renaming the package to "hasql-cursor". Please check it out at https://github.com/nikita-volkov/hasql-cursor.

I haven't tested it anywhere yet, so I haven't released it yet. It would be a great help if you test it out or better make a PR with some tests.

**Comment by nikita-volkov** [comment]
Okay. It's now tested and released as two libraries with different levels of abstraction:

* ["hasql-cursor-query"](https://github.com/nikita-volkov/hasql-cursor-query) - the higher-level abstraction;
* ["hasql-cursor-transaction"](https://github.com/nikita-volkov/hasql-cursor-transaction) - the lower-level abstraction.
