### ISSUE TITLE
[Question] Encoder for hstore?

### ISSUE THREAD

**Issue by forgetaboutit** [nikita-volkov/hasql#56]
First, thank you for creating the library!

I'm currently experimenting with `hstore` and I was wondering how I'd insert/update `hstore` columns. I couldn't find an encoder for `hstore` even though the `postgresql-binary` includes one. Do I have to roll my own or is there already a combinator I overlooked?

**Comment by nikita-volkov** [comment]
As far as I recall I had problems finding the standard OID of `hstore`. OID is required to implement the encoder. But I don't remember really. If you manage to find it, the encoder won't be hard to implement.

Since the newer structures like `jsonb` are considered to surpass `hstore`, I never gave this issue a high priority.

**Comment by forgetaboutit** [comment]
I also couldn't find the OID of `hstore`. I didn't know `jsonb` obsoletes `hstore`, but I guess I'll just use that instead. Thank you!
