### ISSUE TITLE
Encoder for a list of values

### ISSUE THREAD

**Issue by rikvdkleij** [nikita-volkov/hasql#61]
How do I create an encoder for a list or array of values?

For example, query is:
`select id from foo where id in ($1)`

and given: `[Int64]`

**Comment by nikita-volkov** [comment]
There's no support for that in the binary protocol, however you can easily work around that using the `any` and `all` Postgres functions, as per [the docs](https://www.postgresql.org/docs/9.6/static/functions-comparisons.html#AEN20944).

I've also just committed some tests showing it in action:
https://github.com/nikita-volkov/hasql/blob/4c33da4d9fbeb88e999dea4197cd6de5ee089a39/tasty/Main.hs#L25-L59

**Comment by agrafix** [comment]
I hit this issue too, it would be really cool to have an `In` newtype like postgresql-simple that does support writing `... WHERE id IN ($1)`. What that be possible?

**Comment by nikita-volkov** [comment]
1. `... WHERE id IN ($1)` is identical to `... WHERE id = ANY ($1)`, where the value for `$1` is encoded as an array. So that functionality is already at our disposal.

2. It is the way Postgres authors intended these operators to work. Working around that behaviour fixes nothing, introduces overhead and leans the users to use Postgres unidiomatically.

2. The "postgresql-simple" `In` trick is merely impossible to implement in Hasql. "postgresql-simple" can only do that because it does the replaces the placeholders itself on the Haskell end and doesn't support prepared statements, neither of which applies to Hasql.

**Comment by agrafix** [comment]
Sounds reasonable. Even if this is not really the "fault" of hasql, I think it would be awesome to add a "CAUTION" note somewhere in the encoder docs, at least that would have helped me. What do you think? I'd be happy to send a PR.

**Comment by nikita-volkov** [comment]
Sure, man! Finally I'll get a PR from you :)

**Comment by rikvdkleij** [comment]
@nikita-volkov Thanks! It works :smile:
