### ISSUE TITLE
Newbie question: Defining encoders/decoders in record syntax?

### ISSUE THREAD

**Issue by saurabhnanda** [nikita-volkov/hasql#75]
Looking at https://hackage.haskell.org/package/hasql-0.19.18/docs/Hasql-Encoders.html#t:Params I'm wondering if it's possible to have an encoder for `Person` in the record syntax. We have tables with a large number of columns with similar data-types and anything to do with positional parameters has a high change of errors.

**Comment by nikita-volkov** [comment]
How would you map such an encoder to the query without generating the query itself and thus introducing a giant level of abstraction like a DSL or (God forbid!) ORM?

What Hasql will get in the foreseeable future is a quasiquoter, which will do something like the following:

```haskell
personsBornAfter :: Day -> Session (Vector (Text, Day))
personsBornAfter after =
  [session|
    SELECT name, birthday 
    FROM person 
    WHERE birthday > $after"
  |]
```

I think that might be something that you're looking for, because then you'd be able to do something like the following:

```haskell
personsBornAfter :: Person -> Session (Vector (Text, Day))
personsBornAfter person =
  [session|
    SELECT name, birthday 
    FROM person 
    WHERE birthday > $after"
  |]
  where
    after = error "extract the value from 'person'"
```

Or even

```haskell
personsBornAfter :: Person -> Session (Vector (Text, Day))
personsBornAfter Person{..} =
  [session|
    SELECT name, birthday 
    FROM person 
    WHERE birthday > $after"
  |]
```

**Comment by saurabhnanda** [comment]
I'm not sure I completely understand what you mean by this:

> How would you map such an encoder to the query without generating the query itself and thus introducing a giant level of abstraction like a DSL or (God forbid!) ORM?

I was expecting some form of the following:

```
Person  {
  name = encoder blah
, email = encode blah
...
}
```

**Comment by nikita-volkov** [comment]
Okay. Give me a complete example of what you expect, including the whole query declaration, placeholders and what not.

**Comment by leemhenson** [comment]
I'm interested in this topic, but from the decoding side rather than the encoding side. I feel that the ability to decode to a record by mapping column names to field names would be less brittle and more ergonomic. I've experimented with https://github.com/chris-kahn/hasql-generic which handles the "decoding to a record" side of things, but it still needs the columns in the `select` to match exactly the order of fields in the record definition.

I'm happy to have a crack at this myself (despite being a complete beginner in Haskell 😅) if I could get a bit of guidance of the best way to approach it?

Ideally I want to be able to do something like:

```sql
select * from people
``` 

to map cleanly onto:

```hs
data Person = Person
  { personId :: UUID
  , personName :: Text
  , personAge :: Int
  }
```

irrespective of the column order in the query results.

**Comment by nikita-volkov** [comment]
@leemhenson I've created a dedicated issue for your post. Let's move the discussion there.
