### ISSUE TITLE
Begin/commit/rollback support?

### ISSUE THREAD

**Issue by erikd** [nikita-volkov/hasql#82]
I'm looking at using Hasql as a replacement for postgresql-simple, but it seems Hasql doesn't have the `begin`, `commit` and `rollback` operations. I had a look at hasql-transaction, but that doesn't have them either.

Any idea what would be required to add these? Which package should then be added to?

**Comment by karls** [comment]
Just jumping in here.

I suspect those operations are not exposed by `hasql-transaction` because you're meant to use the higher-level API (using `query` and `transaction) which will also provide an automatic retry mechanism.

If you really want those low level operations, you could just define them yourself — they're trivial (https://github.com/nikita-volkov/hasql-transaction/blob/master/library/Hasql/Transaction/Private/Queries.hs#L12-L25). But you would need to handle errors resulting from your query and rollback/abort/retry accordingly, effectively duplicating what `hasql-transaction` would be doing for you.

**Comment by erikd** [comment]
Ok, i may be completely off target. Is there any example or demo code anywhere? I'm having a lot of trouble figuring out how this all fits together.

**Comment by karls** [comment]
I can give you a high-level, bottom-up overview.

- Use `statement` from the `Hasql.Query` module to construct your `Query`.
- Use `query` from the `Hasql.Transaction` module to construct a `Transaction` from `Query` (or multiple queries).
- Use `transaction` from the `Hasql.Transaction.Sessions` module to construct a `Session` from your `Transaction`.
- Use `run` from the `Hasql.Session` module to execute the `Session`.

I haven't tested this code, but a concrete (but dumb) example would look something like

```
let session = transaction Serializable Write $ do
  let dealSize = 100
  query dealSize (statement "update accounts set balance = balance - $1 where id = 123" (value int4) unit)
  query dealSize (statement "update accounts set balance = balance + $1 where id = 456" (value int4) unit)
run session connection
```

Let me know if this helps at all!

**Comment by erikd** [comment]
Thanks @karls, thats a good step in the right direction. Still a bit lost as to where `Serializable` and `Read` come from.

**Comment by karls** [comment]
@erikd sorry, should've been clearer. They both come from the `Hasql.Transaction` module.

`Write` constructor — https://hackage.haskell.org/package/hasql-transaction-0.5.1/docs/Hasql-Transaction.html#t:Mode
`Serializable` constructor — https://hackage.haskell.org/package/hasql-transaction-0.5.1/docs/Hasql-Transaction.html#t:IsolationLevel

You will need to specify those when you turn your `Transaction` into a `Session` with `transaction` (from https://hackage.haskell.org/package/hasql-transaction-0.5.1/docs/Hasql-Transaction-Sessions.html).

**Comment by nikita-volkov** [comment]
@karls Thanks for jumping in!

@erikd Is your question resolved? Can we close this now?

**Comment by erikd** [comment]
Sure.Closing.
